spring:
  datasource:
    postgres:
      jdbc-url: jdbc:postgresql://localhost:54320/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

jwt:
  signingKey: 'oix8Neiceo9aeth3eice'
  aTokenDuration: 30